### ISSUE TITLE
Debugger enabled crashes android app because of outdated dependency

### ISSUE THREAD

**Issue by daralthus** [redbadger/pride-london-app#89]
Reproduction

1. `yarn run-android`
2. `cmd+m` in the emulator
3. Enable remote js debugging
4. Visit `http://localhost:8081/debugger-ui/` 
5. Confirm that the app connects to the debugger then immediately crashes.

Logs

```
04-04 10:16:51.374 10541 10580 E AndroidRuntime: FATAL EXCEPTION: mqt_js
04-04 10:16:51.374 10541 10580 E AndroidRuntime: Process: com.pridelondonapp.dev, PID: 10541
04-04 10:16:51.374 10541 10580 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getOpenSourceSoftwareLicenseInfo(Landroid/content/Context;)Ljava/lang/String; in class Lcom/google/android/gms/common/GoogleApiAvailability; or its super classes (declaration of 'com.google.android.gms.common.GoogleApiAvailability' appears in /data/app/com.pridelondonapp.dev-1/base.apk)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapModule.getConstants(AirMapModule.java:50)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:140)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
04-04 10:16:51.375 12813 13249 W ActivityManager:   Force finishing activity com.pridelondonapp.dev/com.pridelondonapp.MainActivity
```

[This issue](https://github.com/react-community/react-native-maps/issues/1571) seems to be the cause. Updating react-native-maps to the latest solves the problem. PR is coming soon.

**Comment by markholland** [comment]
This worked for me https://stackoverflow.com/a/49003356/1450638
Also https://github.com/facebook/react-native/issues/17970#issuecomment-385904897
